services:
  api-gateway:
    image: devopsfaith/krakend:latest
    container_name: ops-krakend
    network_mode: "host"
    ports:
      - "8080:8080"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
      - ./jwk.json:/etc/krakend/jwk.json
    extra_hosts:
      - "host.docker.internal:host-gateway"

  message-broker:
    image: redis:7-alpine
    container_name: ops-redis
    command: redis-server --requirepass seal_super_secret
    ports:
      - "6380:6379"
